version: "3.8"

services:
  strapi:
    build: .
    ports:
      - "1337:1337"
    volumes:
      - .:/app
      - /app/node_modules  # prevent overwriting container's node_modules with host
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: sqlite
    command: npm run develop
